//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _18338173_bg {
            get {
                object obj = ResourceManager.GetObject("18338173_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _19366_bg {
            get {
                object obj = ResourceManager.GetObject("19366_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock_30 {
            get {
                object obj = ResourceManager.GetObject("clock_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] data_account {
            get {
                object obj = ResourceManager.GetObject("data_account", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] data_info_company {
            get {
                object obj = ResourceManager.GetObject("data_info_company", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stt,logo_name,company_name,location,field,people,country,working_day,time
        ///1,logo-1.png,Nimble,&quot;Ho Chi Minh, Da Nang&quot;,Outsourcing,51-150,Thailand,Monday - Friday,No OT
        ///2,logo-2.png,Easy IT Solutions,&quot;District 3, Ho Chi Minh&quot;,Outsourcing,51-150,Vietnam,Monday - Friday,No OT
        ///3,logo-3.png,Vietnam International Bank (VIB),&quot;Ha Noi, Ho Chi Minh&quot;,Product,1000+,Vietnam,Monday - Friday,none
        ///4,logo-4.png,Robert Bosch Engineering And Business Solutions,&quot;Ho Chi Minh, Ha Noi&quot;,Product,18264,Germany,Monday - Friday,No  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data_info_company_csv {
            get {
                return ResourceManager.GetString("data_info_company_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] data_work {
            get {
                object obj = ResourceManager.GetObject("data_work", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stt,logo_name,company_name,title,salary,distance_time,feature_new_text,skill,location_detail,reason_job,job_description,skill_experience,love_working,slogan
        ///1,logo-1.png,Nimble,Mobile Engineer (Android/Flutter),&quot;2,000 - 3,200 USD&quot;,21m,Hot,Android-Flutter,&quot;WeWork, Lim Tower 3, 03-101, 29A Nguyễn Đình Chiểu, Đa Kao Ward, District 1, Ho Chi Minh&quot;,&quot;High-spec Macbook Pro and kits
        ///WFH and Education Allowances
        ///World-class projects&quot;,&quot;What You Will Do
        ///You will be part of the development team in a project squad with [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data_work_csv {
            get {
                return ResourceManager.GetString("data_work_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dollar_30 {
            get {
                object obj = ResourceManager.GetObject("dollar_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap group_30 {
            get {
                object obj = ResourceManager.GetObject("group_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap internet_30 {
            get {
                object obj = ResourceManager.GetObject("internet_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap location_30 {
            get {
                object obj = ResourceManager.GetObject("location_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap office_building_30 {
            get {
                object obj = ResourceManager.GetObject("office-building_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap schedule_30 {
            get {
                object obj = ResourceManager.GetObject("schedule_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_40 {
            get {
                object obj = ResourceManager.GetObject("search_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings_30 {
            get {
                object obj = ResourceManager.GetObject("settings_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
